### ISSUE TITLE
大佬求助一直报 Cannot read properties of undefined (reading 'length')这个

### ISSUE THREAD

**Issue by SimpleMD** [Lhcfl/hexo-theme-anatolo#11]
$ hexo s
INFO  Validating config
INFO  
=============================================
Welcome from Anatolo!
=============================================
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
Unhandled rejection TypeError: E:\myGithub\my-logs\themes\Anatolo\layout\partial\nav.pug:3
    1| .page-top.animated.fadeInDown
    2|   .nav
  > 3|     each cur, lst in theme.menu
    4|       li

Cannot read properties of undefined (reading 'length')
    at eval (eval at wrap (E:\myGithub\my-logs\node_modules\hexo-renderer-pug\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:72:32)
    at eval (eval at wrap (E:\myGithub\my-logs\node_modules\hexo-renderer-pug\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:119:4)
    at template (eval at wrap (E:\myGithub\my-logs\node_modules\hexo-renderer-pug\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:961:7)
    at _View._compiled (E:\myGithub\my-logs\node_modules\hexo\lib\theme\view.js:136:50)    at _View.render (E:\myGithub\my-logs\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\myGithub\my-logs\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\myGithub\my-logs\node_modules\bluebird\js\release\util.js:16:23)
    at E:\myGithub\my-logs\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\myGithub\my-logs\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:988:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Lhcfl** [comment]
如果我没猜错，这说明你没有设置theme.menu
