### ISSUE TITLE
运行过程中提示Script load failed 错误，请教下如何处理

### ISSUE THREAD

**Issue by cdz-me** [Lhcfl/hexo-theme-anatolo#13]
报错信息：

$ hexo clean && hexo g && hexo s
INFO  Validating config
ERROR Script load failed: themes\Anatolo\scripts\index.js
TypeError: require(...) is not a function
    at Object.<anonymous> (D:\CodeStudy\Hexo-resume\themes\Anatolo\includes\tasks\welcome.js:1:35)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at req (D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\hexo\index.js:240:31)
    at D:\CodeStudy\Hexo-resume\themes\Anatolo\scripts\index.js:1:72
    at D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\hexo\index.js:248:20
    at tryCatcher (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
INFO  Deleted database.
INFO  Deleted public folder.
INFO  Validating config
ERROR Script load failed: themes\Anatolo\scripts\index.js
TypeError: require(...) is not a function
    at Object.<anonymous> (D:\CodeStudy\Hexo-resume\themes\Anatolo\includes\tasks\welcome.js:1:35)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at req (D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\hexo\index.js:240:31)
    at D:\CodeStudy\Hexo-resume\themes\Anatolo\scripts\index.js:1:72
    at D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\hexo\index.js:248:20
    at tryCatcher (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
INFO  Start processing
INFO  Files loaded in 1.07 s
ERROR
TypeError: D:\CodeStudy\Hexo-resume\themes\Anatolo\layout\mixins.pug:55
    53|             span.leancloud_visitors
    54|             span
  > 55|               - var words = word_count(item.content)
    56|               - var needtime = duration((words / 300.0) * 60, 'seconds')
    57|               - var timestr = (time(needtime, "m") == '0' ? "" : (time(needtime, "m") + __('time.minu'))) + time(needtime, "s") + __("time.senc")
    58|               = __("article.about") + words + __("article.words") + ", " + timestr + __("article.read")

word_count is not a function
    at Object.pug_interp [as make_post] (eval at wrap (D:\CodeStudy\Hexo-resume\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1512:13)
    at eval (eval at wrap (D:\CodeStudy\Hexo-resume\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1615:24)
    at template (eval at wrap (D:\CodeStudy\Hexo-resume\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:2329:7)
    at _View._compiled (D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\theme\view.js:125:67)
    at _View.render (D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\theme\view.js:50:21)
    at D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\hexo\index.js:58:29
    at tryCatcher (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\util.js:16:23)
    at D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\hexo\router.js:43:9)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR
TypeError: D:\CodeStudy\Hexo-resume\themes\Anatolo\layout\mixins.pug:55
    53|             span.leancloud_visitors
    54|             span
  > 55|               - var words = word_count(item.content)
    56|               - var needtime = duration((words / 300.0) * 60, 'seconds')
    57|               - var timestr = (time(needtime, "m") == '0' ? "" : (time(needtime, "m") + __('time.minu'))) + time(needtime, "s") + __("time.senc")
    58|               = __("article.about") + words + __("article.words") + ", " + timestr + __("article.read")

word_count is not a function
    at Object.pug_interp [as make_post] (eval at wrap (D:\CodeStudy\Hexo-resume\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1261:13)
    at eval (eval at wrap (D:\CodeStudy\Hexo-resume\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1364:24)
    at _Query.forEach (D:\CodeStudy\Hexo-resume\node_modules\warehouse\dist\query.js:34:13)
    at eval (eval at wrap (D:\CodeStudy\Hexo-resume\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1111:12)
    at template (eval at wrap (D:\CodeStudy\Hexo-resume\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1651:7)
    at _View._compiled (D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\theme\view.js:125:67)
    at _View.render (D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\theme\view.js:50:21)
    at D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\hexo\index.js:58:29
    at tryCatcher (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\util.js:16:23)
    at D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\hexo\router.js:43:9)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
INFO  Generated: index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2023/index.html
INFO  Generated: images/favicon.webp
INFO  Generated: images/gongan.png
INFO  Generated: images/logo.webp
INFO  Generated: images/logo@2x.webp
INFO  Generated: fonts/fontawesome-webfont.woff
INFO  Generated: css/blog_basic.css
INFO  Generated: css/search.css
INFO  Generated: css/insight.css
INFO  Generated: css/theme/mixin_functions.css
INFO  Generated: css/theme/base.css
INFO  Generated: js/friends-link-generator.js
INFO  Generated: css/font-awesome.css
INFO  Generated: fonts/fontawesome-webfont.woff2
INFO  Generated: css/comments/gittalk.css
INFO  Generated: css/font-awesome.min.css
INFO  Generated: css/theme/light.css
INFO  Generated: js/darkLightToggle.js
INFO  Generated: js/jquery.appear.js
INFO  Generated: archives/2023/11/index.html
INFO  Generated: js/site.js
INFO  Generated: js/jquery-migrate-1.2.1.min.js
INFO  Generated: js/insight.js
INFO  Generated: css/style.css
INFO  Generated: js/add-bookmark.js
INFO  Generated: js/baidu-tongji.js
INFO  Generated: css/theme/dark.css
INFO  Generated: js/router.js
INFO  Generated: js/tagcloud.js
INFO  Generated: js/url_for.js
INFO  Generated: js/tagcanvas.js
INFO  Generated: fonts/fontawesome-webfont.eot
INFO  Generated: js/visitors.js
INFO  Generated: fonts/fontawesome-webfont.ttf
INFO  Generated: 2023/11/07/hello-world/index.html
INFO  Generated: js/jquery.js
INFO  Generated: fonts/FontAwesome.otf
INFO  Generated: fonts/fontawesome-webfont.svg
INFO  40 files generated in 395 ms
INFO  Validating config
ERROR Script load failed: themes\Anatolo\scripts\index.js
TypeError: require(...) is not a function
    at Object.<anonymous> (D:\CodeStudy\Hexo-resume\themes\Anatolo\includes\tasks\welcome.js:1:35)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at req (D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\hexo\index.js:240:31)
    at D:\CodeStudy\Hexo-resume\themes\Anatolo\scripts\index.js:1:72
    at D:\CodeStudy\Hexo-resume\node_modules\hexo\dist\hexo\index.js:248:20
    at tryCatcher (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\CodeStudy\Hexo-resume\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
INFO  See you again

**Comment by Lhcfl** [comment]
你肯定没装依赖，看readme.md去npm install把依赖装上

如果还有问题把cjs的引擎卸掉
